/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { MigrationsContract } from './Migrations'

declare global {
	namespace Truffle {
		interface Artifacts {
			require(name: 'Migrations'): MigrationsContract
		}
	}
}

export { MigrationsContract, MigrationsInstance } from './Migrations'
